# Generated by Django 3.2.23 on 2024-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('airhelp', models.FloatField(max_length=10)),
                ('ponctualite', models.FloatField(max_length=10)),
                ('avis', models.FloatField(max_length=10)),
                ('service', models.FloatField(max_length=10)),
            ],
        ),
    ]
